export default {

    PROFILES_RECEIVED: "PROFILES_RECEIVED",
    PROFILE_CREATED: "PROFILE_CREATED",
    CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED",
    BOOKMARKS_RECEIVED: "BOOKMARKS_RECEIVED",
    BOOKMARK_CREATED: "BOOKMARK_CREATED",
    PROFILE_SELECTED: "PROFILE_SELECTED"

}
